### ISSUE TITLE
[FEATURE] Implement BPM changes / BPM Slider

### ISSUE THREAD

**Issue by Crafty-The-Fox** [Septem151/gifsync#31]
**BPM Changes don't work**
When songs start, the BPM is mostly lower for me and that results in the gif being slower than intended, or if possible add a manually BPM slider of some sorts

**Implement BPM slider**
If possible, id like to see BPM changes happen without tinkering, but if the spotify API does not allow that a BPM slider will suffice

**Comment by Septem151** [comment]
I do like this idea. A custom BPM entry option is something I’ve wanted to add for awhile. It wouldn’t be too difficult to implement, and my JavaScript knowledge has definitely increased since writing this repo.

I want to refactor most of how GifSync works, but I could try to squeeze in this feature.

FYI: If your gif isn’t already playing at 1 beats per loop, try halving the value. This will double the speed at which your gif plays.

**Comment by Crafty-The-Fox** [comment]
> I do like this idea. A custom BPM entry option is something I’ve wanted to add for awhile. It wouldn’t be too difficult to implement, and my JavaScript knowledge has definitely increased since writing this repo.
> 
> I want to refactor most of how GifSync works, but I could try to squeeze in this feature.
> 
> FYI: If your gif isn’t already playing at 1 beats per loop, try halving the value. This will double the speed at which your gif plays.

alright, thanks for the quick response. il make sure to half the value

**Comment by Septem151** [comment]
Custom Tempo entry is now available. Works regardless of if a song is playing on Spotify. Clear the custom Tempo to revert back to the currently playing song's Tempo (assuming you have a song currently playing on Spotify).
