### ISSUE TITLE
[FEATURE] Ability to set half speed for faster bpm

### ISSUE THREAD

**Issue by Rainyote** [Septem151/gifsync#41]
It would be cool to have a feature that automatically sets the gif to play at half speed if the bpm of the current song is over a certain threshold. I have a gif of a character nodding, and when set to the beat of lower bpm songs (80-120) it works perfectly, but faster bpm songs (130+) just look silly. 

Sometimes (I've found most notably with alternative tracks) the bpm is very high for a very mellow song. So for example, while Spotify pulls the bpm as 180, the song sounds more like 90, so a hyper fast gif doesn't "match up". If there were a limiter in place, I could set it to (for example) 130, so anything above that bpm plays at half speed, while anything below it plays at the current set speed.

**Comment by Septem151** [comment]
Good idea, thanks for the suggestion. I will take a look into this. There are two ways for approach:

A global settings menu to clip tempos

Pros:
- Simpler to implement
- Can be extended upon to support future features in the settings menu

Cons:
- Will apply a tempo clip to all songs playing, regardless of the gif

Per gif setting to clip tempo.

Pros:
- More customizable to have different settings apply to different gifs

Cons:
- Harder to implement & takes up more database space


I'm thinking I'll go with the Settings menu approach, since I'd rather not touch the database models. Plus, the user cookie is being underutilized regardless, and aligns more with my vision of how GifSync will work in the full release which allows guest logins and Spotify integrations.

So planned features are:

- [ ] Settings Menu UI
- [ ] "Min Tempo" setting that will double tempo past a set threshold
- [ ] "Max Tempo" setting that will halve tempo past a set threshold

**Comment by Septem151** [comment]
Featured added, along with Custom Tempo selection as well.
